### ISSUE TITLE
why not make the description the readme?

### ISSUE THREAD

**Issue by tlambert03** [jni/affinder#63]
The description page @DragaDoncila made here is lovely.  why not just make it the readme?   There's nothing in there that isn't generally applicable to the plugin, and it would make for a much nicer presentation on github, pypi, etc...

**Comment by jni** [comment]
I don't think there's any particular reason @tlambert03! 😊 I *think* back when she made it we couldn't have mp4s render in READMEs? 🤷

**Comment by GenevieveBuckley** [comment]
Also, this description page is not included anywhere in the main docs at https://jni.github.io/affinder/ I think it should be included there too. 

If you actually do make the description be the readme, perhaps that takes care of that problem (since the README is copied into the docs website).

**Comment by GenevieveBuckley** [comment]
And can I just say how much I hate having napari-hub require a separate description file, instead of using the README. You inevitably end up with this type of problem, where one is better than the other and only some of the information is in certain places. 

I've heard all the arguments about how they're supposed to be two different documents aimed at different audience, but it just never seems to actually work out better in practice.

**Comment by DragaDoncila** [comment]
> Also, this description page is not included anywhere in the main docs at https://jni.github.io/affinder/ I think it should be included there too.

It is included under [usage](https://jni.github.io/affinder/usage.html) but the home page needs attention to make this obvious. I think I remember @jamesyan-git working on this and having to jump through a bunch of hoops to just include the DESCRIPTION.md doc rather than having to duplicate the information.

I'm actually +1 to just getting rid of the DESCRIPTION.md and making it the README. Like Genevieve says, the original argument that you'd maintain a separate description for the napari hub is maybe, nice, but I don't think it's nicer than having complete documentation on the docs website and on the repo. Keeping both in sync manually is a nightmare, so I think if the napari-hub wants to be able to display "subsets" of the information in the plugin's docs or README, there should be a mechanism to mark existing documentation as `hub-relevant` or something, rather than having to maintain a separate doc.

**Comment by DragaDoncila** [comment]
> And can I just say how much I hate having napari-hub require a separate description file, instead of using the README.

The napari hub btw does use the README if one is available and no DESCRIPTION file is present.

**Comment by tlambert03** [comment]
> And can I just say how much I hate having napari-hub require a separate description file, instead of using the README.

you could add your voice to the hub discussion over in their repo :joy:   more core devs saying this might actually make them budge a bit

**Comment by GenevieveBuckley** [comment]
> > And can I just say how much I hate having napari-hub require a separate description file, instead of using the README.
> 
> The napari hub btw does use the README if one is available and no DESCRIPTION file is present.

The napari hub linter tool (or preview tool? I don't know what you call it) absolutely complains at you if there is no description file present. It's absolutely considers my plugins "unfinished" for the napari hub in that respect.

**Comment by GenevieveBuckley** [comment]
>> And can I just say how much I hate having napari-hub require a separate description file, instead of using the README.
>
> you could add your voice to the hub discussion over in their repo 😂 more core devs saying this might actually make them budge a bit: https://github.com/chanzuckerberg/napari-hub/discussions/627

Ok, done: https://github.com/chanzuckerberg/napari-hub/discussions/627#discussioncomment-5668469

**Comment by DragaDoncila** [comment]
> The napari hub linter tool (or preview tool? I don't know what you call it) absolutely complains at you if there is no description file present. It's absolutely considers my plugins "unfinished" for the napari hub in that respect.

Perhaps. But a README is always used if available and there's no DESCRIPTION file. If you find that's not the case, that's a bug.

**Comment by GenevieveBuckley** [comment]
> > The napari hub linter tool (or preview tool? I don't know what you call it) absolutely complains at you if there is no description file present. It's absolutely considers my plugins "unfinished" for the napari hub in that respect.
> 
> Perhaps. 

There's no perhaps about it, I'm telling you what the behaviour is.

> But a README is always used if available and there's no DESCRIPTION file. If you find that's not the case, that's a bug.

Yes, I already know this happens. That's slightly off-topic from the [point I made here](https://github.com/jni/affinder/issues/63#issuecomment-1515635619) though.
